[package]
name = "leptos-tiptap"
version = "0.2.0"
edition = "2021"
rust-version = "1.70"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptos-tiptap"
description = """
Tiptap integration for leptos projects.
"""
categories = ["gui"]
keywords = ["tiptap", "leptos", "components", "editor", "wysiwyg"]

[dependencies]
leptos = "0.4"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.5"
tracing = "0.1"
urlencoding = "2"
wasm-bindgen = "0.2"
